version: '3.8'
services:
  backend:
    build: .
    container_name: api_backend
    ports:
      - '5001:5001'
    volumes:
      - ./:/app
    command: npm run db

  frontend:
    build: .
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: npm run start
